// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {kitsulanv1} from '../models';

export function CheckServerStatus():Promise<boolean>;

export function ConnectToServer(arg1:string):Promise<boolean>;

export function CreateChannel(arg1:string,arg2:string,arg3:number):Promise<kitsulanv1.Channel>;

export function CreateGuild(arg1:string,arg2:string):Promise<kitsulanv1.Guild>;

export function CreateInvite(arg1:string,arg2:number,arg3:number):Promise<string>;

export function DeleteGuild(arg1:string):Promise<void>;

export function GetHistory(arg1:string,arg2:number,arg3:string):Promise<Array<kitsulanv1.ChatMessage>>;

export function JoinByInvite(arg1:string):Promise<kitsulanv1.Guild>;

export function LeaveGuild(arg1:string):Promise<void>;

export function ListChannels(arg1:string):Promise<Array<kitsulanv1.Channel>>;

export function ListMembers(arg1:string):Promise<Array<kitsulanv1.Member>>;

export function ListMyGuilds():Promise<Array<kitsulanv1.Guild>>;

export function Login(arg1:string,arg2:string):Promise<string>;

export function Register(arg1:string,arg2:string):Promise<string>;

export function SendMessage(arg1:string,arg2:string):Promise<kitsulanv1.ChatMessage>;

export function SetToken(arg1:string):Promise<void>;

export function SubscribeChannel(arg1:string):Promise<void>;

export function UnsubscribeChannel():Promise<void>;
